//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭкзаменСавинов.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public string Фамилия { get; set; }
        public string Имя__отчество { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public double Роли { get; set; }
    
        public virtual Роли Роли1 { get; set; }
    }
}
