//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭкзаменСавинов.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public double Стоимость { get; set; }
        public double Размер_максимально_возможной_скидки { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public double Категория_товара { get; set; }
        public double Действующая_скидка { get; set; }
        public double Кол_во_на__складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    
        public virtual КатегорииТоваров КатегорииТоваров { get; set; }
    }
}
